# Use a slim Python 3.9 image
FROM python:3.9-slim

# Copy the entire application into /app
COPY . /app
WORKDIR /app

# Install the requirements
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Expose the required port
EXPOSE 5000

# Define environment variables
ENV MODEL_NAME mini
ENV APP_MODULE mini
ENV SERVICE_TYPE MODEL
ENV PERSISTENCE 0

# Change ownership of the /app directory
RUN chown -R 8888 /app

# Command to start the Seldon microservice
CMD ["seldon-core-microservice", "$MODEL_NAME", "--service-type", "$SERVICE_TYPE", "--persistence", "$PERSISTENCE"]